CREATE TABLE customer
(
    id    NUMBER(38, 0) NOT NULL,
    name  VARCHAR2(255),
    email VARCHAR2(255),
    CONSTRAINT pk_customer PRIMARY KEY (id)
);

CREATE TABLE product
(
    id          NUMBER(38, 0) NOT NULL,
    name        VARCHAR2(255),
    qty         VARCHAR2(255),
    price       NUMBER(38, 0),
    customer_id NUMBER(38, 0),
    CONSTRAINT pk_product PRIMARY KEY (id)
);

ALTER TABLE product
    ADD CONSTRAINT FK_PRODUCT_ON_CUSTOMER FOREIGN KEY (customer_id) REFERENCES customer (id);

DROP SEQUENCE "LOGMNR_EVOLVE_SEQ$";

DROP SEQUENCE "LOGMNR_SEQ$";

DROP SEQUENCE "LOGMNR_UIDS$";

DROP SEQUENCE "MVIEW$_ADVSEQ_GENERIC";

DROP SEQUENCE "MVIEW$_ADVSEQ_ID";

DROP SEQUENCE "REPCAT$_EXCEPTIONS_S";

DROP SEQUENCE "REPCAT$_FLAVORS_S";

DROP SEQUENCE "REPCAT$_FLAVOR_NAME_S";

DROP SEQUENCE "REPCAT$_REFRESH_TEMPLATES_S";

DROP SEQUENCE "REPCAT$_REPPROP_KEY";

DROP SEQUENCE "REPCAT$_RUNTIME_PARMS_S";

DROP SEQUENCE "REPCAT$_TEMPLATE_OBJECTS_S";

DROP SEQUENCE "REPCAT$_TEMPLATE_PARMS_S";

DROP SEQUENCE "REPCAT$_TEMPLATE_REFGROUPS_S";

DROP SEQUENCE "REPCAT$_TEMPLATE_SITES_S";

DROP SEQUENCE "REPCAT$_TEMP_OUTPUT_S";

DROP SEQUENCE "REPCAT$_USER_AUTHORIZATIONS_S";

DROP SEQUENCE "REPCAT$_USER_PARM_VALUES_S";

DROP SEQUENCE REPCAT_LOG_SEQUENCE;

DROP SEQUENCE "TEMPLATE$_TARGETS_S";